namespace ElVegetarianoFurio.Core
{
    // Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
    // If you change the class to 'public' in order to use it outside its assembly
    //  you should also change the fields from 'const' to 'public static readonly'
    static class FaSolid
    {
        public const string Home = "\uf015";
        public const string Utensils = "\uf2e7";
        public const string Carrot = "\uf787";
        public const string UtensilSpoon = "\uf2e5";
        public const string PepperHot = "\uf816";
        public const string IceCream = "\uf810";
        public const string GlassCheers = "\uf79f";
        public const string UserCircle = "\uf2bd";
        public const string MapMarkedAlt = "\uf5a0";
        public const string Phone = "\uf095";
    }
}