namespace ImagesSample
{
    // Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
    // If you change the class to 'public' in order to use it outside its assembly
    //  you should also change the fields from 'const' to 'public static readonly'
    static class FaIcons
    {
        /// <summary>
        /// Zeigt ein Zeitungssymbol an
        /// </summary>
        public const string Newspaper = "\uf1ea";


        /// <summary>
        /// Symbol zum Teilen von Inhalten
        /// </summary>
        public const string ShareSquare = "\uf14d";
        public const string Envelope = "\uf0e0";
        public const string User = "\uf007";
        public const string Clock = "\uf017";

    }
}